### ISSUE TITLE
Question: why not use --format=png in scanimage ?

### ISSUE THREAD

**Issue by jakubczaplicki** [wurzelfenster-org/Wurzelfenster#1]
Why do you use TIFF output, and then convert it to PNG instead of setting PNG format : `scanimage --mode=color --resolution=$dpi --format=png -l0 -t0 -x215 -y297 > $scanDir$filename.png` ? Does it give better output ?

**Comment by wurzelfenster-org** [comment]
Hey Jakub,
thank you for the question! 
we originally saved the tiff as well, because of the greater color depth. 
You can however also directly scan as a png!

**Comment by jakubczaplicki** [comment]
@wurzelfenster-org  : Thanks for adding me to the repo ! :)
I am working on automating one wurzelscanner for my son's preschool, so prepare for some incoming PRs. :)
