### ISSUE TITLE
Silly Question: how can I edit wiki ?

### ISSUE THREAD

**Issue by jakubczaplicki** [wurzelfenster-org/Wurzelfenster#2]
I wanted to add this change: 
```
diff --git a/Wurzelscanner.md b/Wurzelscanner.md
index 1534c2e..fff557e 100644
--- a/Wurzelscanner.md
+++ b/Wurzelscanner.md
@@ -10,13 +10,16 @@
 - 4 x [3D-Printed G-Clamp](https://www.thingiverse.com/thing:1673030)
 - seal tape
 - scanner (make sure your scanner is supported by SANE: http://www.sane-project.org/sane-supported-devices.html 
-            & there is a driver for the raspberry pi)
+            & there is a driver for the raspberry pi - some 3rd party binaries are not available for ARM chips)
     - tested scanners:
+        - EPSON perfection 1250 Photo (*)
         - EPSON perfection 1670
         - EPSON perfection 2400 Photo
         - EPSON perfection 2480
         - EPSON perfection 2580
-        
+
+* works OK despite SANE claiming it's incompatible
+


 shell
-pi@raspberrypi:~# nano scanCount.txt
+pi@raspberrypi:~# touch scanCount.txt
 ```

but got : 

```
$ git push origin add_epson_1250_photo
remote: Permission to wurzelfenster-org/Wurzelfenster.wiki.git denied to jakubczaplicki.
fatal: unable to access 'https://github.com/wurzelfenster-org/Wurzelfenster.wiki.git/': The requested URL returned error: 403
```

**Comment by JulesDoe** [comment]
Hey thank you very much for being the first contributing to this project!
all that it tells you is that you doesn't have the rights to directly push to the main branch of this repo. 
The github way of contributing is as follows:
-fork the repo to your own account ✓
-push changes to *your fork* of the repo
-after you finished your work create a pull request
That pullrequest we than can review and merge into the main repository :)

Actualy the easyest way for souch small changes is to fork and use the github online editor to make the changes. That way you dont have to clone it to your mashine first.

**Comment by jakubczaplicki** [comment]
Thanks @JulesDoe . That's what I did, but it seems that forking a project doesn't fork wiki.
And even though it is possible to git clone wiki, I don't see how to fork it ?

**Comment by jakubczaplicki** [comment]
Oh and there's no edit button. Is the github online editor disabled for public editing ? I must say that I do know github, but I've always been a part of a project so never had such permission issues :)

**Comment by JulesDoe** [comment]
Hmm same here.. :D sry
It seems that GitHub doesn't supports pull requests for the wiki repository.
I enabled public wiki editing.. nice suggestion thanks! :)
